name: CI - Validate and Policy Gate

on:
  pull_request:
    paths:
      - 'terraform/**'
      - 'policies/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login with Service Principal secret
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt

      - name: Terraform Plan to JSON
        working-directory: terraform
        run: |
          terraform validate
          terraform plan \
            -out=plan.out \
            -var="location=${{ vars.AZURE_LOCATION }}" \
            -var="resource_group_name=${{ vars.AZURE_RG }}" \
            -var="storage_account_name=raas${{ github.run_id }}"
          terraform show -json plan.out > plan.json

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
          soft_fail: true

      - name: Install Conftest
        run: |
          curl -L https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64.tar.gz | tar zx
          sudo mv conftest /usr/local/bin/conftest

      - name: Conftest OPA Policy Gate
        run: conftest test terraform/plan.json -p policies

      - name: Summarize in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            ## Security Gate Results
            - Terraform validated and planned.
            - Checkov and OPA evaluated the plan.
            - If this workflow fails, the Auto Fix workflow will propose a remediation PR.
